runtime: python
api_version: 1
threadsafe: 1
env: flex
entrypoint: gunicorn main:app

runtime_config:
   python_version: 3

# [START handlers]
#handlers:
#- url: /.*
#  script: main.app
# [END handlers]